"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Sparkles, Download, Send, Shield } from "lucide-react";
import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import LoadingVideoRotator from "../components/LoadingVideoRotator";
import { buildPromptText, type ChangeFocus } from "../lib/generation/buildPrompt";
import { buildNegativePrompt } from "../lib/generation/buildNegativePrompt";
import { generateWithComfy } from "../lib/generation/comfyClient";
import { featureIdsToLabels, lightIdsToLabels } from "../lib/features";

const ROOM_LABELS: Record<string, string> = {
  hallway: "Прихожая",
  kitchen: "Кухня",
  living: "Гостиная",
  bathroom: "Ванная",
  bedroom: "Спальня",
  kids: "Детская",
  balcony: "Балкон"
};

function CreateContent() {
  const searchParams = useSearchParams();
  const plan = searchParams.get("plan");
  const roomsParam = searchParams.get("rooms") || "";
  const rooms = useMemo(() => roomsParam.split(",").filter(Boolean), [roomsParam]);
  const style = searchParams.get("style");
  const brightness = searchParams.get("brightness");
  const contrast = searchParams.get("contrast");
  const lighting = searchParams.get("lighting");
  const palette = searchParams.get("palette");
  const time = searchParams.get("time");
  const zodiacSign = searchParams.get("zodiacSign");
  const zodiacVibe = searchParams.get("zodiacVibe");
  const family = searchParams.get("family");
  const features = searchParams.get("features");
  const lightFeatures = searchParams.get("lightFeatures");
  const targetRooms = useMemo(() => (family ? [family] : rooms), [family, rooms]);

  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [elapsedSeconds, setElapsedSeconds] = useState<number | null>(null);
  const [lockView, setLockView] = useState(false);
  const [variationStrength, setVariationStrength] = useState(35);
  const [changeFocus, setChangeFocus] = useState<ChangeFocus>("decor");
  const [lightingVariantLabel, setLightingVariantLabel] = useState<string | null>(null);
  const [sourceImageFile, setSourceImageFile] = useState<File | null>(null);
  const [sourceImagePreview, setSourceImagePreview] = useState<string | null>(null);
  const [isBuying, setIsBuying] = useState(false);
  const hasAutoGenerated = useRef(false);
  const lockedSeedRef = useRef(Math.floor(Math.random() * 1_000_000_000));
  const generationCounterRef = useRef(0);
  const lastGeneratedImageRef = useRef<string | null>(null);

  useEffect(() => {
    lastGeneratedImageRef.current = generatedImage;
  }, [generatedImage]);

  const comfyApiUrl = "/api/comfy";
  const comfyModel = process.env.NEXT_PUBLIC_COMFY_MODEL || "flux1-schnell-Q4_K_S.gguf";
  const fluxClipName1 = process.env.NEXT_PUBLIC_FLUX_CLIP_1 || "clip_l.safetensors";
  const fluxClipName2 = process.env.NEXT_PUBLIC_FLUX_CLIP_2 || "t5xxl_fp8_e4m3fn.safetensors";
  const fluxVaeName = process.env.NEXT_PUBLIC_FLUX_VAE || "ae.safetensors";
  const fluxMaxShift = Number(process.env.NEXT_PUBLIC_FLUX_MAX_SHIFT || "1.15");
  const fluxBaseShift = Number(process.env.NEXT_PUBLIC_FLUX_BASE_SHIFT || "0.5");
  const fluxWidth = Number(process.env.NEXT_PUBLIC_FLUX_WIDTH || "1024");
  const fluxHeight = Number(process.env.NEXT_PUBLIC_FLUX_HEIGHT || "1024");
  const fluxLora1Name = process.env.NEXT_PUBLIC_FLUX_LORA_1_NAME || "";
  const fluxLora1StrengthModel = Number(process.env.NEXT_PUBLIC_FLUX_LORA_1_STRENGTH_MODEL || "0.6");
  const fluxLora1StrengthClip = Number(process.env.NEXT_PUBLIC_FLUX_LORA_1_STRENGTH_CLIP || "1.0");
  const fluxLora2Name = process.env.NEXT_PUBLIC_FLUX_LORA_2_NAME || "";
  const fluxLora2StrengthModel = Number(process.env.NEXT_PUBLIC_FLUX_LORA_2_STRENGTH_MODEL || "0.5");
  const fluxLora2StrengthClip = Number(process.env.NEXT_PUBLIC_FLUX_LORA_2_STRENGTH_CLIP || "1.0");
  const publicBaseUrl = process.env.NEXT_PUBLIC_PUBLIC_BASE_URL || (typeof window !== "undefined" ? window.location.origin : "");
  const starsCostCandidate = Number(process.env.NEXT_PUBLIC_STARS_PER_GENERATION || "1");
  const starsCost = Number.isFinite(starsCostCandidate) && starsCostCandidate > 0
    ? Math.floor(starsCostCandidate)
    : 1;
  const starPacks = useMemo(() => ([
    { id: "pack_50", label: "50 ⭐" },
    { id: "pack_150", label: "150 ⭐" },
    { id: "pack_500", label: "500 ⭐" }
  ]), []);
  const [remoteLoadingVideos, setRemoteLoadingVideos] = useState<string[]>([]);
  const loadingVideos = useMemo(() => {
    const raw = process.env.NEXT_PUBLIC_LOADING_VIDEOS || "";
    if (!raw) return [];
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) {
        return parsed.filter((value): value is string => typeof value === "string" && Boolean(value.trim()));
      }
    } catch {
      return raw.split(",").map(item => item.trim()).filter(Boolean);
    }
    return [];
  }, []);
  const effectiveLoadingVideos = loadingVideos.length ? loadingVideos : remoteLoadingVideos;
  const loadingVideoIntervalMs = useMemo(() => {
    const raw = process.env.NEXT_PUBLIC_LOADING_INTERVAL_MS;
    const parsed = raw ? Number(raw) : NaN;
    if (!Number.isFinite(parsed)) return 0;
    return Math.max(3000, Math.min(120000, Math.floor(parsed)));
  }, []);

  useEffect(() => {
    if (loadingVideos.length) return;
    const provider = process.env.NEXT_PUBLIC_LOADING_PROVIDER;
    if (provider !== "pixabay") return;
    
    const query = process.env.NEXT_PUBLIC_LOADING_QUERY || "ai videos";
    console.log(`[LoadingVideos] Fetching videos from Pixabay API for query: "${query}"`);
    
    const params = new URLSearchParams({ q: query, perPage: "20" });
    fetch(`/api/loading-videos/pixabay?${params.toString()}`)
      .then(res => {
        if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
        return res.json();
      })
      .then(data => {
        const videos = Array.isArray(data?.videos) ? data.videos : [];
        console.log(`[LoadingVideos] Successfully loaded ${videos.length} videos from Pixabay.`);
        setRemoteLoadingVideos(videos);
      })
      .catch(err => {
        console.error("[LoadingVideos] Failed to fetch loading videos:", err);
        return;
      });
  }, [loadingVideos.length]);

  const promptText = useMemo(() => {
    return buildPromptText({
      plan,
      rooms: targetRooms,
      style,
      brightness,
      contrast,
      lighting,
      palette,
      time,
      zodiacSign,
      family,
      features,
      lightFeatures,
      changeFocus
    });
  }, [plan, targetRooms, style, brightness, contrast, lighting, palette, time, zodiacSign, family, features, lightFeatures, changeFocus]);

  const sendToTelegram = useCallback(async (imageUrl: string, caption: string) => {
    if (!imageUrl.startsWith("http")) return;
    try {
      await fetch("/api/telegram/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ imageUrl, caption })
      });
    } catch {
      return;
    }
  }, []);

  const sendToCabinet = useCallback(async (initData: string, imageUrl: string, caption: string) => {
    if (!initData) return;
    if (!imageUrl.startsWith("http")) return;
    await fetch("/api/telegram/cabinet/send", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ initData, imageUrl, caption })
    }).catch(() => null);
  }, []);

  const handleSourceImageChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] || null;
    setSourceImageFile(file);
    if (!file) {
      setSourceImagePreview(null);
      return;
    }
    setLockView(false);
    const reader = new FileReader();
    reader.onload = () => {
      const result = typeof reader.result === "string" ? reader.result : null;
      setSourceImagePreview(result);
    };
    reader.readAsDataURL(file);
  }, []);

  const handleSaveImage = useCallback(() => {
    if (!generatedImage) return;
    const link = document.createElement("a");
    link.href = generatedImage;
    link.download = `ferma-design-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [generatedImage]);

  const handleSendTelegramManual = useCallback(async () => {
    if (!generatedImage) return;
    const chatId = prompt("Введите username (@user) или ID чата для отправки:");
    if (!chatId) return;
    
    try {
      await fetch("/api/telegram/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          imageUrl: generatedImage, 
          caption: "Сгенерировано в Ferma Design",
          chatId: chatId
        })
      });
      alert("Отправлено!");
    } catch {
      alert("Ошибка отправки.");
    }
  }, [generatedImage]);

  const handleGenerate = useCallback(async () => {
    console.log('[DEBUG] handleGenerate called, isGenerating:', isGenerating);
    if (isGenerating) return;
    console.log('[DEBUG] Starting generation...');
    setIsGenerating(true);
    const startTime = performance.now();
    console.log(`[Metrics] Generation started at ${new Date().toISOString()}`);
    
    setGenerateError(null);
    setElapsedSeconds(0);
    setGeneratedImage(null);
    const telegramInitData =
      typeof window !== "undefined" ? window.Telegram?.WebApp?.initData || "" : "";
    try {
      if (telegramInitData) {
        fetch("/api/metrics/track", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            initData: telegramInitData,
            event: "generation_start",
            data: {
              plan,
              style,
              rooms,
              family,
              features,
              lightFeatures,
              starsCost
            }
          })
        }).catch(() => null);
      }

      if (telegramInitData && starsCost > 0) {
        const checkResponse = await fetch("/api/stars/check", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ initData: telegramInitData, amount: starsCost })
        });
        const checkPayload = await checkResponse.json().catch(() => ({}));
        const allowed = checkResponse.ok && checkPayload?.ok === true && checkPayload?.allowed === true;
        if (!allowed) {
          const currentStars = typeof checkPayload?.stars === "number" ? checkPayload.stars : 0;
          setGenerateError(`Недостаточно звёзд: ${currentStars}/${starsCost}. Открой личный кабинет в Telegram (чат бота), чтобы пополнить баланс.`);
          setElapsedSeconds(null);
          return;
        }
      }

      generationCounterRef.current += 1;
      const generationIndex = generationCounterRef.current;
      const randomPick = <T,>(items: T[]) => items[Math.floor(Math.random() * items.length)];
      const rotatingPick = (items: string[]) => items[generationIndex % items.length];
      const effectiveChangeFocus: ChangeFocus = changeFocus;
      const previousGeneratedImage = lastGeneratedImageRef.current;
      const lightingScenarios = [
        {
          label: "Ночь",
          prompt: "night interior scene, strictly no daylight, windows show pitch black exterior, no visible outside details, warm artificial interior lighting only, ceiling lights on, sconces and chandelier on, night ambiance, realistic indoor exposure, moody shadows, deep contrast, warm highlights",
          negative: "daylight, sun rays, bright daytime windows, blue sky outside, clouds visible outside, sunset sky, golden hour outside, illuminated exterior background"
        }
      ];
      const focusPromptMap: Record<ChangeFocus, string[]> = {
        decor: [
          "refresh decor accents and textiles while preserving architecture",
          "update pillows, throws, art and tabletop decor only",
          "swap decorative objects and soft furnishings only"
        ],
        lighting: [
          "change only the lighting mood and fixture glow intensity",
          "adjust lighting scenario while keeping materials unchanged",
          "shift to a new lighting setup with same furniture and layout"
        ],
        materials: [
          "change only material finishes and surface textures",
          "update wood, stone and fabric finishes only",
          "refresh material palette while preserving decor placement"
        ],
        hardware: [
          "change only handles, pulls, faucets and metallic accents with precise geometry while keeping full-room framing",
          "refresh furniture hardware and fixture details only, keep perfect alignment and full interior context",
          "update chandelier and handle finish details only with realistic engineering proportions in a full room shot"
        ]
      };
      const focusNegativeMap: Record<ChangeFocus, string> = {
        decor: "changed room layout, replaced furniture geometry, changed architecture",
        lighting: "new furniture, changed materials, changed room layout, changed decor arrangement, changed object placement, replaced cabinetry",
        materials: "new furniture arrangement, changed decor layout, changed camera angle",
        hardware: "new furniture geometry, changed wall colors, changed room layout, bent handles, warped handles, asymmetrical handles, deformed sconces, crooked fixture arms, floating hardware, duplicated handles"
      };
      const hardwareStrict = effectiveChangeFocus === "hardware";
      const lightingStrict = lockView && effectiveChangeFocus === "lighting";
      console.log('[DEBUG] lockView:', lockView, 'changeFocus:', effectiveChangeFocus, 'lightingStrict:', lightingStrict);
      let selectedLightingScenario: { label: string; prompt: string; negative: string } | null = null;
      if (effectiveChangeFocus === "lighting") {
        selectedLightingScenario = lightingScenarios[0];
        setLightingVariantLabel(selectedLightingScenario.label);
        console.log('[DEBUG] selectedLightingScenario:', selectedLightingScenario);
      } else {
        setLightingVariantLabel(null);
      }
      const cameraVariation = lockView
        ? "same camera position, same camera height, same perspective, same framing"
        : hardwareStrict
          ? "straight-on framing, perspective-corrected view, 20mm lens"
          : "ultra wide angle, 18mm lens, wide field of view, expansive room view";
      const compositionVariation = lockView
        ? "same room layout and same composition"
        : "balanced composition, clean architectural framing, show floor and ceiling";
      const variationIntensityText =
        lightingStrict
          ? "very subtle variation"
          : hardwareStrict && variationStrength >= 70
          ? "moderate variation"
          : variationStrength < 30
          ? "very subtle variation"
          : variationStrength < 70
            ? "moderate variation"
            : "noticeable variation";
      const sourceImageFurnishingPrompt = sourceImageFile
        ? "if room is empty or sparsely furnished, must add complete functional furniture set, seating, storage, textiles, lighting fixtures and decor; never leave room empty; create dense but realistic furnishing across all room zones; if room is already furnished, preserve key furniture and enrich styling; deliver move-in-ready finished interior while preserving original architecture"
        : "";
      const sourceImageDensityPrompt = sourceImageFile
        ? "avoid under-furnished look, avoid single furniture piece composition, add anchor furniture group plus secondary storage and layered decor, fill center and perimeter zones with balanced circulation"
        : "";
      const focusPrompt = lightingStrict
        ? sourceImageFile
          ? `change lighting scenario: ${selectedLightingScenario?.prompt}; if room is empty or sparse, add full furniture set and decor while preserving architecture`
          : `change only lighting scenario: ${selectedLightingScenario?.prompt}, keep all furniture, decor and materials exactly unchanged`
        : lockView ? rotatingPick(focusPromptMap[effectiveChangeFocus]) : randomPick(focusPromptMap[effectiveChangeFocus]);
      const depthPrompt = lightingStrict
        ? "same optical depth and same focus plane"
        : "deep depth of field, sharp focus everywhere, no blur, corner to corner sharpness";
      const atmospherePrompt =
        effectiveChangeFocus === "lighting"
          ? "moody night ambiance, warm practical lighting, no daylight, preserve furniture and layout"
          : lightingStrict
            ? "preserve room mood and composition, change illumination only"
            : "cozy and airy atmosphere, natural light, inviting space";
      const texturePrompt = lightingStrict
        ? "same textures and same materials"
        : "high quality materials, detailed textures, realistic surfaces";
      const preserveScenePrompt = lightingStrict
        ? "same furniture geometry, same object placement, same material finishes, same decor composition"
        : "";
      const sourceImageLayoutPrompt = sourceImageFile
        ? "respect uploaded room geometry, keep original window and door positions exactly, preserve wall openings and circulation paths, arrange furniture based on real room layout without blocking windows and doors, maintain exact room dimensions and proportions, preserve architectural features like arches, niches, columns, do not move or resize windows, do not move or resize doors, keep ceiling height and floor plan exactly as uploaded"
        : "";
      const bathroomLayoutPrompt = family === "bathroom"
        ? "single vanity with one sink only, avoid double vanity, no duplicate sinks; avoid interior windows looking into the bathroom; if there is a window, make it a privacy frosted window with no visible interior view"
        : "";
      const kitchenLayoutPrompt = family === "kitchen"
        ? "enclosed kitchen space, interior shot of a self-contained kitchen, no living room visible, no open-plan layout, view showing only the kitchen area"
        : "";
      const fullScenePrompt = "full room interior shot, include furniture layout and architectural context, avoid isolated object framing, physically plausible furniture support structures, clean straight chair legs, clean straight table legs, correct cabinet feet geometry, symmetrical legs, correct perspective on legs and bases";
      const variations = [
        fullScenePrompt,
        sourceImageLayoutPrompt,
        sourceImageFurnishingPrompt,
        sourceImageDensityPrompt,
        cameraVariation,
        depthPrompt,
        atmospherePrompt,
        compositionVariation,
        texturePrompt,
        variationIntensityText,
        focusPrompt,
        preserveScenePrompt,
        bathroomLayoutPrompt,
        kitchenLayoutPrompt,
        hardwareStrict ? "perfectly straight vertical lines, symmetrical wall fixture geometry, precise hardware alignment" : ""
      ].filter(Boolean).join(", ");
      const finalPrompt = `${promptText}, ${variations}`;
      const lightingStrictNegative = lightingStrict
        ? ", changed furniture, changed sofa shape, changed table shape, changed cabinetry, changed decor placement, changed material texture"
        : "";
      const lightingScenarioNegative = selectedLightingScenario?.negative ? `, ${selectedLightingScenario.negative}` : "";
      const sourceImageLayoutNegative = sourceImageFile
        ? ", moved window, moved door, extra window, extra door, missing window, missing door, blocked doorway, blocked window, furniture blocking door, furniture blocking window, changed wall openings, wrong room geometry"
        : "";
      const sourceImageFurnitureNegative = sourceImageFile
        ? ", empty room, unfurnished room, bare room, no furniture, no decor, only walls and floor, vacant interior, showroom shell, empty center floor, empty corners, unfurnished zones, sparse furniture, underfurnished interior, single bench in empty room, single ottoman in empty room, lone furniture piece"
        : "";
      const focusNegative = sourceImageFile && effectiveChangeFocus !== "hardware"
        ? "changed architecture, moved window, moved door, blocked openings, wrong room geometry"
        : focusNegativeMap[effectiveChangeFocus];
      const negativePromptBase = buildNegativePrompt({
        focusNegative,
        lockView,
        lightingStrictNegative,
        lightingScenarioNegative,
        sourceImageLayoutNegative,
        sourceImageFurnitureNegative
      });
      const bathroomNegative = family === "bathroom"
        ? ", double vanity, two sinks, dual sinks, his and hers sinks, duplicated sink, duplicate vanity, interior window, window looking into bathroom, clear bathroom window to interior, bathroom display window"
        : "";
      const kitchenNegative = family === "kitchen"
        ? ", open plan, open-plan, studio apartment, combined kitchen living room, kitchen-living room, living room area, sofa, couch, armchair, coffee table, TV, media console"
        : "";
      const negativePrompt = `${negativePromptBase}${bathroomNegative}${kitchenNegative}${lightingStrictNegative}${lightingScenarioNegative}`;
      console.log('[DEBUG] Final prompt:', finalPrompt);
      console.log('[DEBUG] Negative prompt:', negativePrompt);
      console.log('[DEBUG] lightingScenarioNegative:', lightingScenarioNegative);

      const captionBudgetLabel = plan === "premium" ? "Высокий" : plan === "optimal" ? "Средний" : "Эконом";
      const captionParts = [
        plan ? `Бюджет: ${captionBudgetLabel}` : null,
        style ? `Стиль: ${style}` : null,
        targetRooms.length ? `Комнаты: ${targetRooms.map(room => ROOM_LABELS[room] || room).join(", ")}` : null,
        family ? `Семья: ${ROOM_LABELS[family] || family}` : null,
        features ? `Дополнительные предметы: ${featureIdsToLabels(style, family, features).join(", ")}` : null,
        lightFeatures ? `Свет: ${lightIdsToLabels(style, family, lightFeatures).join(", ")}` : null,
        zodiacSign ? `Знак: ${zodiacSign}${zodiacVibe ? ` · ${zodiacVibe}` : ""}` : null,
        `Вариация: ${effectiveChangeFocus}`,
        sourceImageFile ? "Источник: фото комнаты" : "Источник: текстовый рендер",
        selectedLightingScenario ? `Свет: ${selectedLightingScenario.label}` : null,
        lockView ? "Ракурс: фиксирован" : "Ракурс: свободный"
      ].filter(Boolean).join("\n");
      const seed = lockView ? lockedSeedRef.current : Math.floor(Math.random() * 1_000_000_000);
      const comfySteps = 6;
      const comfyCfg = 1.0;
      const comfyDenoise = sourceImageFile ? 0.7 : 1;
      const maxWaitSeconds = sourceImageFile ? 180 : 120;
      setElapsedSeconds(0);

      const inputImage = sourceImageFile ? sourceImageFile : lightingStrict ? previousGeneratedImage : null;
      const fluxLoras = [
        fluxLora1Name ? { name: fluxLora1Name, strengthModel: fluxLora1StrengthModel, strengthClip: fluxLora1StrengthClip } : null,
        fluxLora2Name ? { name: fluxLora2Name, strengthModel: fluxLora2StrengthModel, strengthClip: fluxLora2StrengthClip } : null
      ].filter(Boolean) as Array<{ name: string; strengthModel: number; strengthClip: number }>;
      const comfyResult = await generateWithComfy({
        apiBaseUrl: comfyApiUrl,
        publicBaseUrl: publicBaseUrl || window.location.origin,
        modelNameCandidates: [comfyModel],
        controlNetCandidates: [],
        engine: "flux_gguf",
        fluxClipName1,
        fluxClipName2,
        fluxVaeName,
        fluxMaxShift,
        fluxBaseShift,
        fluxLoras,
        clientId: "ferma_web",
        finalPrompt,
        negativePrompt: negativePrompt,
        seed,
        steps: comfySteps,
        cfg: comfyCfg,
        denoise: comfyDenoise,
        controlNetStrength: 0,
        controlNetStartPercent: 0,
        controlNetEndPercent: 0,
        width: fluxWidth,
        height: fluxHeight,
        inputImage,
        useControlNet: false,
        maxWaitSeconds,
        onTick: seconds => setElapsedSeconds(seconds)
      });

      setGeneratedImage(comfyResult.imageUrl);
      setElapsedSeconds(null);

      const endTime = performance.now();
      const duration = ((endTime - startTime) / 1000).toFixed(2);
      console.log(`[Metrics] Generation success! Duration: ${duration}s. Image: ${comfyResult.imageUrl.substring(0, 50)}...`);

      if (telegramInitData) {
        fetch("/api/metrics/track", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            initData: telegramInitData,
            event: "generation_success",
            data: {
              durationSec: Number(duration),
              plan,
              style,
              rooms,
              family,
              starsCost
            }
          })
        }).catch(() => null);
      }

      if (telegramInitData && starsCost > 0) {
        await fetch("/api/stars/spend", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ initData: telegramInitData, amount: starsCost })
        }).catch(() => null);
      }

      void sendToTelegram(comfyResult.imageUrl, captionParts);
      void sendToCabinet(telegramInitData, comfyResult.imageUrl, captionParts);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Не удалось получить изображение из API.";
      console.error(`[Metrics] Generation failed. Error: ${message}`);
      if (telegramInitData) {
        fetch("/api/metrics/track", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            initData: telegramInitData,
            event: "generation_error",
            data: {
              message,
              plan,
              style,
              rooms,
              family,
              starsCost
            }
          })
        }).catch(() => null);
      }
      setGenerateError(message);
      setElapsedSeconds(null);
    } finally {
      setIsGenerating(false);
    }
  }, [
    isGenerating,
    lockView,
    variationStrength,
    changeFocus,
    sourceImageFile,
    promptText,
    comfyApiUrl,
    comfyModel,
    fluxClipName1,
    fluxClipName2,
    fluxVaeName,
    fluxMaxShift,
    fluxBaseShift,
    fluxWidth,
    fluxHeight,
    fluxLora1Name,
    fluxLora1StrengthModel,
    fluxLora1StrengthClip,
    fluxLora2Name,
    fluxLora2StrengthModel,
    fluxLora2StrengthClip,
    starsCost,
    plan,
    style,
    rooms,
    targetRooms,
    family,
    features,
    lightFeatures,
    zodiacSign,
    zodiacVibe,
    publicBaseUrl,
    sendToTelegram,
    sendToCabinet
  ]);

  const isReady = Boolean(plan && style && targetRooms.length);
  const displayPlan = plan === "premium" ? "Высокий" : plan === "optimal" ? "Средний" : "Эконом";
  const displayStyle =
    style === "modern" ? "Современный" :
    style === "neoclassic" ? "Неоклассика" :
    style === "eco" ? "Джапанди и Эко-стиль" :
    style === "scandinavian" ? "Скандинавский интерьер" :
    style || "";
  const displayRooms = targetRooms.map(room => ROOM_LABELS[room] || room).join(", ");
  const focusOptions: Array<{ value: ChangeFocus; label: string }> = [
    { value: "decor", label: "Декор" },
    { value: "lighting", label: "Свет" },
    { value: "materials", label: "Материалы" },
    { value: "hardware", label: "Фурнитура" }
  ];
  useEffect(() => {
    if (isReady && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      void handleGenerate();
    }
  }, [isReady, handleGenerate]);

  return (
    <div className="flex flex-col items-center justify-center w-full max-w-5xl mx-auto gap-6">
      <div className="text-center space-y-2">
        <h1 className="text-2xl md:text-3xl font-bold text-[#856c45] text-center font-serif">
          Ваш интерьер
        </h1>
        <h2 className="text-lg font-semibold text-gray-800">
          {displayStyle}
        </h2>
                {zodiacSign && (
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#856c45]/10 rounded-full mt-2">
            <Sparkles className="w-3 h-3 text-[#856c45]" />
            <span className="text-xs font-medium text-[#856c45]">
              Учтены особенности знака {zodiacSign}: {zodiacVibe}
            </span>
          </div>
        )}
      </div>

      <div className="relative p-4 bg-white rounded-xl shadow-2xl border border-[#e3d3b8] w-full">
        {/* Параметры интерьера */}
        <div className="mb-4 p-3 bg-[#fdfbf7] rounded-lg border border-[#e3d3b8]/30">
          <h3 className="text-sm font-semibold text-[#856c45] mb-2">Выбранные параметры:</h3>
          <div className="flex flex-wrap gap-2">
            {brightness && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Яркость: {brightness === 'dim' ? 'Приглуш.' : brightness === 'normal' ? 'Норма' : 'Ярко'}
              </span>
            )}
            {contrast && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Контраст: {contrast === 'soft' ? 'Мягкий' : contrast === 'natural' ? 'Естеств.' : 'Высокий'}
              </span>
            )}
            {lighting && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Освещение: {lighting === 'warm' ? 'Теплое' : lighting === 'neutral' ? 'Нейтр.' : 'Холодное'}
              </span>
            )}
            {palette && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Палитра: {palette === 'mono' ? 'Моно' : palette === 'pastel' ? 'Пастель' : 'Насыщ.'}
              </span>
            )}
            {time && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Время: {time === 'morning' ? 'Утро' : time === 'day' ? 'День' : 'Ночь'}
              </span>
            )}
            {family && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Помещение: {ROOM_LABELS[family] || family}
              </span>
            )}
            {features && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Дополнительные предметы: {featureIdsToLabels(style, family, features).join(", ")}
              </span>
            )}
            {lightFeatures && (
              <span className="px-2 py-1 bg-white text-xs rounded-full border border-[#856c45]/20 text-[#856c45]">
                Свет: {lightIdsToLabels(style, family, lightFeatures).join(", ")}
              </span>
            )}
          </div>
        </div>
        
        <div className="relative w-full aspect-[4/3] overflow-hidden rounded-sm border border-gray-200 bg-[#fdfbf7]">
          {generatedImage && !isGenerating ? (
            <img
              src={generatedImage}
              alt="Generated Interior"
              className="w-full h-full object-contain"
            />
          ) : (
            <div className="absolute inset-0 flex flex-col bg-[radial-gradient(circle_at_top,#f7efe3,#fdfbf7)]">
              <div className="relative flex-1 overflow-hidden">
                {isGenerating && (
                  <LoadingVideoRotator videos={effectiveLoadingVideos} intervalMs={loadingVideoIntervalMs} />
                )}
                <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-white/60" />
              </div>
              <div className="flex flex-col items-center justify-center gap-1 px-4 py-5 bg-white/70 backdrop-blur-[3px] border-t border-[#e3d3b8]">
                <div className="w-10 h-10 border-4 border-[#856c45] border-t-transparent rounded-full animate-spin" />
                <div className="text-sm text-[#856c45]">
                  Ожидаем результат генерации
                </div>
                {isGenerating && elapsedSeconds !== null && (
                  <div className="text-xs text-[#856c45]/80 text-center">
                    <div>Прошло ~{elapsedSeconds} сек</div>
                    <div>
                      {sourceImageFile
                        ? "Время генерации по своему фото может доходить до 80 сек"
                        : "Среднее время генерации: 50 сек"}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Блок загрузки фото комнаты под окном генерации */}
      <div className="w-full p-4 bg-[#fdfbf7] rounded-lg border border-[#e3d3b8]/30">
        <div className="flex flex-col md:flex-row gap-4 items-start md:items-center">
          <div className="flex-shrink-0">
            <div className="text-sm font-semibold text-[#856c45] mb-2">📸 Загрузить фото комнаты</div>
            <div className="text-xs text-gray-600 mb-2 max-w-md">
              Загрузите фото комнаты (пустой или с мебелью) для генерации интерьера с сохранением окон, дверей и размеров
            </div>
            <input
              type="file"
              accept="image/*"
              onChange={handleSourceImageChange}
              disabled={isGenerating}
              className="w-full md:w-auto text-xs text-[#856c45] file:mr-2 file:rounded-md file:border-0 file:bg-[#856c45] file:px-2 file:py-1 file:text-white"
            />
          </div>
          
          <div className="flex-1 flex flex-col md:flex-row gap-4">
            {sourceImagePreview && (
              <div className="flex flex-col gap-2">
                <div className="text-xs text-[#856c45] font-medium">
                  ✅ Фото загружено - окна и двери зафиксированы
                </div>
                <div className="flex gap-2 items-center">
                  <img
                    src={sourceImagePreview}
                    alt="Источник комнаты"
                    className="w-24 h-24 object-cover rounded-md border border-[#e3d3b8]"
                  />
                  <button
                    type="button"
                    onClick={() => {
                      setSourceImageFile(null);
                      setSourceImagePreview(null);
                    }}
                    disabled={isGenerating}
                    className="px-3 py-1 text-xs rounded-md border border-[#e3d3b8] text-[#856c45] hover:bg-[#f8f1e6]"
                  >
                    Убрать фото
                  </button>
                </div>
              </div>
            )}
            
            {!sourceImagePreview && (
              <div className="text-xs text-gray-500 space-y-1">
                <div>💡 <strong>Важно:</strong> при загрузке фото автоматически фиксируются:</div>
                <div className="flex flex-wrap gap-2">
                  <span className="bg-white px-2 py-1 rounded border border-[#e3d3b8]/30">• Положение окон и дверей</span>
                  <span className="bg-white px-2 py-1 rounded border border-[#e3d3b8]/30">• Размеры и геометрия комнаты</span>
                  <span className="bg-white px-2 py-1 rounded border border-[#e3d3b8]/30">• Архитектурные особенности</span>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="w-full grid gap-3 md:grid-cols-[1fr_auto_1fr] md:items-center">
        <div className="p-3 rounded-xl border border-[#e3d3b8] bg-white">
          <label className="flex items-center gap-2 text-sm text-[#856c45] font-medium">
            <input
              type="checkbox"
              checked={lockView}
              onChange={event => setLockView(event.target.checked)}
              disabled={isGenerating}
              className="accent-[#856c45]"
            />
            Зафиксировать ракурс
          </label>
          <div className="mt-3">
            <div className="text-xs text-[#856c45] mb-1">
              Вариации: {variationStrength <= 25 ? "Аккуратно" : variationStrength <= 55 ? "Баланс" : "Смело"}
            </div>
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setVariationStrength(20)}
                disabled={isGenerating}
                className={`px-2 py-2 text-xs rounded-lg border transition-colors ${
                  variationStrength <= 25
                    ? "bg-[#856c45] text-white border-[#856c45]"
                    : "bg-white text-[#856c45] border-[#e3d3b8] hover:bg-[#f8f1e6]"
                }`}
              >
                Аккуратно
              </button>
              <button
                type="button"
                onClick={() => setVariationStrength(35)}
                disabled={isGenerating}
                className={`px-2 py-2 text-xs rounded-lg border transition-colors ${
                  variationStrength > 25 && variationStrength <= 55
                    ? "bg-[#856c45] text-white border-[#856c45]"
                    : "bg-white text-[#856c45] border-[#e3d3b8] hover:bg-[#f8f1e6]"
                }`}
              >
                Баланс
              </button>
              <button
                type="button"
                onClick={() => setVariationStrength(70)}
                disabled={isGenerating}
                className={`px-2 py-2 text-xs rounded-lg border transition-colors ${
                  variationStrength > 55
                    ? "bg-[#856c45] text-white border-[#856c45]"
                    : "bg-white text-[#856c45] border-[#e3d3b8] hover:bg-[#f8f1e6]"
                }`}
              >
                Смело
              </button>
            </div>
            <div className="mt-1 text-[11px] text-[#856c45]/75">
              Аккуратно — меньше изменений, Смело — больше изменений
            </div>
          </div>
                  </div>

        <div className="flex flex-col items-center gap-2">
          <div className="text-xs text-[#856c45]/75">
            Стоимость генерации: {starsCost} ⭐
          </div>
          <div className="flex flex-wrap gap-2 justify-center">
            {starPacks.map(pack => (
              <button
                key={pack.id}
                type="button"
                disabled={isGenerating || isBuying}
                onClick={async () => {
                  const initData = typeof window !== "undefined" ? window.Telegram?.WebApp?.initData || "" : "";
                  if (!initData) {
                    alert("Открой мини‑апп внутри Telegram, чтобы купить звёзды.");
                    return;
                  }
                  setIsBuying(true);
                  try {
                    const res = await fetch("/api/payments/stars/create-invoice", {
                      method: "POST",
                      headers: { "content-type": "application/json" },
                      body: JSON.stringify({ initData, packageId: pack.id })
                    });
                    const json = await res.json().catch(() => ({}));
                    if (!res.ok || !json?.invoiceLink) {
                      alert(json?.message || "Не удалось создать счёт");
                      return;
                    }
                    const tg = typeof window !== "undefined" ? window.Telegram?.WebApp : undefined;
                    const link = String(json.invoiceLink);
                    if (tg?.openInvoice) {
                      tg.openInvoice(link, status => {
                        if (status === "paid") {
                          setTimeout(() => window.location.reload(), 500);
                        }
                      });
                      return;
                    }
                    if (tg?.openLink) {
                      tg.openLink(link);
                      return;
                    }
                    window.open(link, "_blank", "noopener,noreferrer");
                  } finally {
                    setIsBuying(false);
                  }
                }}
                className="px-3 py-1.5 rounded-full bg-white border border-[#856c45]/20 text-[#856c45] text-[12px] font-bold hover:bg-[#f8f1e6] disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Купить {pack.label}
              </button>
            ))}
          </div>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className={`group flex items-center gap-3 px-8 py-4 rounded-full font-bold text-lg shadow-lg transition-all transform ${
              isGenerating
                ? "bg-[#856c45]/70 text-white cursor-wait"
                : "bg-[#856c45] text-white hover:bg-[#6b5636] hover:shadow-xl hover:-translate-y-1 active:scale-95"
            }`}
          >
            {isGenerating ? "Генерация..." : "Сгенерировать ещё раз"}
            <Sparkles className="w-6 h-6 group-hover:rotate-12 transition-transform" />
          </button>
          
          <div className="flex gap-2 w-full justify-center">
            <button
              onClick={handleSaveImage}
              disabled={!generatedImage || isGenerating}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-[#e3d3b8] rounded-full text-[#856c45] text-sm font-medium hover:bg-[#f8f1e6] disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-sm"
            >
              <Download className="w-4 h-4" />
              Сохранить
            </button>
            <button
              onClick={handleSendTelegramManual}
              disabled={!generatedImage || isGenerating}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-[#e3d3b8] rounded-full text-[#856c45] text-sm font-medium hover:bg-[#f8f1e6] disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-sm"
            >
              <Send className="w-4 h-4" />
              В Telegram
            </button>
          </div>

          {generateError && (
            <div className="text-sm text-red-600">{generateError}</div>
          )}
        </div>

        <div className="p-3 rounded-xl border border-[#e3d3b8] bg-white">
          <div className="text-sm text-[#856c45] font-medium mb-2">Менять только</div>
          <div className="grid grid-cols-2 gap-2">
            {focusOptions.map(option => (
              <button
                key={option.value}
                type="button"
                onClick={() => {
                  setChangeFocus(option.value);
                  if (option.value === "lighting") {
                    setLightingVariantLabel("Ночь");
                  } else {
                    setLightingVariantLabel(null);
                  }
                }}
                disabled={isGenerating}
                className={`px-3 py-2 rounded-lg text-sm border transition-colors ${
                  changeFocus === option.value
                    ? "bg-[#856c45] text-white border-[#856c45]"
                    : "bg-white text-[#856c45] border-[#e3d3b8] hover:bg-[#f8f1e6]"
                }`}
              >
                {option.label}
              </button>
            ))}
          </div>
          {changeFocus === "lighting" && (
            <div className="mt-2 text-xs text-[#856c45]/80">
              Сценарий света: {lightingVariantLabel || "авто"}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function CreatePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-4 md:p-8 bg-[#fdfbf7] text-gray-900 relative">
      <Link href="/" className="absolute top-8 left-8 flex items-center gap-2 text-[#856c45] hover:underline font-medium transition-colors z-50">
        <ArrowLeft className="w-5 h-5" />
        Назад
      </Link>
      <Link
        href="/admin"
        className="absolute top-8 right-8 inline-flex items-center gap-2 px-3 py-2 rounded-full bg-white border border-[#856c45]/20 text-[#856c45] font-bold text-sm shadow-sm hover:bg-[#f8f1e6] transition-colors z-50"
      >
        <Shield className="w-4 h-4" />
        Админка
      </Link>

      <Suspense fallback={<div className="text-[#856c45]">Загрузка...</div>}>
        <CreateContent />
      </Suspense>
    </main>
  );
}
